name: sentiment-gap
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python=3.10
  - pandas
  - numpy
  - scikit-learn
  - gensim
  - nltk
  - spacy
  - streamlit
  - plotly
  - pytest
  - matplotlib
  - seaborn
  - pip
  - nbformat>=4.2.0
  - pip:
    - textblob
    - spacy-lookups-data
